name: tofu

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - env:
          PAT: ${{ secrets.PAT }}
          PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
          TF_VAR_bws_access_token: ${{ secrets.BW_ACCESS_TOKEN }}
        run: |
          tofu init -upgrade
      - env:
          PAT: ${{ secrets.PAT }}
          PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
          TF_VAR_bws_access_token: ${{ secrets.BW_ACCESS_TOKEN }}
        run: |
          GITHUB_TOKEN="${PAT}" tofu \
            apply -auto-approve -input=false -lock=true -no-color
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: "Success"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: "Failure"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: "Cancelled"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
